# Setup
title:        Vermilion
tagline:      A C++ Raytracer
baseurl:      "/Vermilion"
paginate:     1

# About/contact
author:
  name:       Chris Anderson
  url:        https://casperthecat.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown